mysql:
  dns: "root:laios@tcp(localhost:3306)/ginchat?charset=utf8mb4&parseTime=True&loc=Local"

redis:
  addr: "192.168.2.176:6379"
  password: ""
  DB: 6
  poolSize: 30
  minIdleConn: 30


port:
  server: ":8082"
  udp: 3001