mysql:
  dns: "root:123456@tcp(192.168.1.168:3306)/ginchat?charset=utf8mb4&parseTime=True&loc=Local"

redis:
  addr: "192.168.1.168:16379"
  password: ""
  DB: 6
  poolSize: 30
  minIdleConn: 30


port:
  server: ":8082"
  udp: 3001